# This workflow will install Python dependencies, build the html pages using Sphinx, and add the html to the build directory.
# Based on python actions template: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Sphinx build and deploy

on:
  push:
    branches: [ "main", "Pages" ]
  pull_request:
    branches: [ "main", "Pages" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade -r requirements.txt
    - name: Build Sphinx for Github Pages
      run: |
        rm -rf ./docs
        python -m sphinx source docs
    - name: Create .nojekyll
      run: |
        touch ./docs/.nojekyll
    - name: Commit and push changes
      run: |
        git config --global user.name "AP-CSA-JAVA"
        git config --global user.email "AP-CSA-JAVA@users.noreply.github.com"
        git add ./.
        git commit -m "Build latest version"
        git push
